### ISSUE TITLE
Data download error

### ISSUE THREAD

**Issue by Beauty9527** [BilkentCompGen/hercules#11]
Dear Sir,
     I got a trouble when I tried to download the PacBio reads and Illumina reads,the feedback on the website showed "You don't have permission to access /pacbio-complex-regions/reads/CH17-124M20/ on this server." I have tried to use a VPN overseas but failed in the same way.Could you do me a favor to share these reads by another way or reconfigure the server at eichlerlab.gs.washington.edu.
     Much thanks and best wishes!
                                                                                                                                 Yours,sincerely
                                                                                                                                     Beauty Wang

**Comment by calkan** [comment]
Hi

We are not operating that server, so we cannot reconfigure it. But you can find the data on SRA:

https://www.ncbi.nlm.nih.gov/sra/?term=CH17-124M20

**Comment by Beauty9527** [comment]
Dear Sir,
       Thank you very much.This is very important for me.
       Best wishes!
Sincerely Beauty Wang
