### ISSUE TITLE
ERROR: Unexpected character 'M' found. 

### ISSUE THREAD

**Issue by Hulanyue** [BilkentCompGen/hercules#13]
**Hi @calkan ，I have a problem as follows:**
when I run `./hercules -1 -li l.fq -si s.fq -o preprocessing/`.it show me the error:
`Preprocessing has begun...
ERROR: Unexpected character 'M' found. 
Failure on preprocessing step. Check out the errors.
`

**is it because  the s.fq  is not pair-end sequence? the part of seqs are as follow:**
@short_0
TAACCCCCCCGCACAGATACCTAGGGGCGGGACGCGGGATGTTATATCCAGGCAGTTCTCGATGATTTAAAATGCCTCTCCAATAAGACATTGGTGTACT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@short_1
AATCGAGGCATGCCACTCCAATTGGTCAGTTATACGCTCAATCCCTTTGTAAGCTCGGATTTTTACCGACCTTTTTTGCGTAACGTTTCATCCTTATAGA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@short_2
GGTTCTCCCTAAGGTCAACCTCCATCGAAGGTACGGGTTGCCTCAAAAGAAGTCAAAGTCTGAGTCGACATCAGACGCCTCGTATCCCGAAGCCTTGCGA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
.......................

**the l.fq are as follows:**
@long_contamination_0
GAACTTCGCGTCTGCTCCTAATGGTCTCCAAGTCTACATCGCATGTCCTCTCTCATAGTGTCATGTCTAGGTTTCAGATAGGTCTCTACATGCGTGGCCTATTCAATCGGCACTTCGTGTGGAGCATCATATTTGCCAAGATGGACATAGCTTCCGTGGCGCTTACCCTACCCTCATGTATTCATTGAACCGGCAGCGGTTGCAGTCCATCTCGACTCCTGAGTGATTAGGATAGGGCCCGGATCTTGTGCCGTCCTTGAATCATTCTAGGAACCCCGAATGTGTTCGTCCCTGGGCGTATCCGCTCGAGGCGGCCGGGGGATGGCTACCAGCCGGGTCGAGTGATGGTCATGAGTCCCTGCTTTACGGGGTATAGGCACGAATGAGCCCCAACGTGCGGCGTTGCCAGAGAGGATCTGTTCTTTCGGGCAACATGTAGATTTGGGAATTGTAAAGTGACATACTTTTGCCTTCAGCTTCTCCCTGTTGATTTTTAGAGTGTAGCTAAGACGTTGGAATATTCATGCCTTCGCCAGGAACGCCCGTCTAGCGGTTGCCTGTTATTCCGATTAATTCTACCGCAAACTTCATTTTCACCGGCGATTACGCCAAGAAGGACAGGACGGTCGAGACCGCGCTACAAGACGATGTCCAGTGTGACCATGGGTTGGCTTCTAATACCTGCGTAACTCTTTGAGGGGACGCAAGGTTCGTCATGTACGTCTTTGCTGTTATGCCAATAAATTGGTAGCCATTCTCGACACATTTTGGAGTGAGCTGATGTATTGTCCGATTCTATCAGTTAAACTGGCGGAATATGACTGACGGGTTAAGTAAAACCAACACGTTACTCGCAGTGCAAATCTGCCCCCACAGGACTAAACAGGCGCAGATCTAGAAACCGCAACCCAAGAGTTTCCGCTTGAAAAAGGCCCACATATTATATTGGGTTTCCTCTGCCCCCTACTGAAGGTGACGGGCGTTCGTCTGCGCAATACGGTAGGCTAACAGTAACGTGGTGCAAATTAGGATCGCGGCAGTGAAAAAGTGAG
+
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
@long_error_0_0 RSTART:86026 with-iupac-chars
GAGTGAAAAAGTGACGGCGCTAGGATTAAACGTGGTGCAATGACAMTCGGATGGCATAACGCGTCTGCTTGCGGGCAGTGGAAGTCATCCCCCGTCTCCTTTGGGTTATATTATACACCCGGAAAAAGTTCGCCTTTGAGAACCCAACGCCAAAGATCTAGACGCGGACAAATCAGGACACCCCCGTCTAAACGTGACGCTCATTGCACAACCAAAATGAATTGGGCAGTCAGTATAAGGCGGTCAAATTGACTATCTTAGCCTGTTATGTAGTCGAGTGAGGTTTTACACAGCTCTTACCGATGGTTAAATAACCGTATTGTCGTTTCTGCATGTACTGCTTGGAACGCAGGGGAGTTTCTCAATGCGTCCATAATCTTCGGTTGGGTACCAGTGTGACCTGTAGCAGAACATCGCGCCAGAGCTGGCAGGACAGGAAGAACCGCATTAGCGGCCACTTTTACTTCAAACGCCATCTTAATTAGCCTTATTGTCCGTTGGCGATCTGCCCGCAAGGACCGCTTCCGTACTTATAAGGTTGCAGAATCGATGTGAGATTTTTAGTTGTCCCTCTTCGACTTCCGTTTTCATACAGTGAAATGTTAAGGGTTTAGATGTACAACGGGCTTTCTTGTCTAGGAGAGACCGTTGCGGCGTGCAACCCCGAGTAAGCACGGATATGGGGCATTTCGTCCCTGAGTACTGGTAGTGAGCTGGGCCGACCATCGGTAGGGGGCCGGCGGAGCTCGCCTATGCGGGTCCCTGCTTGTGTAAGCCCCAAGGATCTTACTAAGTTCCTGCCGTGTTCTAGGCCCGGGATAGGATTAGTGAGTCCTCAGCTCTACCTGACGTTGGCGACGGCCAAGTTACTTATGTACTCCCATCCCATTCGCGGTGCCTTCGATACAGGTAGAACCGTTTATACTACGAGGTGTGCTTCACGGCTAACTTATCCGGTGCGTACATCTCTGGATAGACTTTGGATCTGTACTGTGATACTCTCTCCTGTACGCTACATCTGAACCTCTGGTAATCCTCGTCTGCGCTTCAAG
+
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
............................

**Comment by canfirtina** [comment]
Hi @Hulanyue ,

Probably you already noticed but Hercules uses the DNA alphabet that Seqan provides (http://docs.seqan.de/seqan/master/?p=Dna). You have character 'M' in your read with id "@long_error_0_0", which is not included in the DNA alphabet.

Best,

Can

**Comment by Hulanyue** [comment]
Okay!I have make it!
F.antasticus_long_error.fq **and**  F.antasticus_long_orig.fq,I used the latter,it is allright!
