### ISSUE TITLE
why no docs ?

### ISSUE THREAD

**Issue by colindaven** [BilkentCompGen/hercules#2]
Hi,
installation seems like a guessing game here, any suggestions ? Directly downloading or cloning seqan ?
cheers
```
 git clone --recursive https://github.com/BilkentCompGen/hercules.git
hercules$ make
g++ -I /usr/local/include/ -std=c++14 -O3 -DNDEBUG -W -Wall -o ../bin/hercules main.cpp -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1 -pedantic -fopenmp -lpthread -lrt -lz -lbz2
In file included from main.cpp:20:0:
CommandLineOptions.h:16:29: fatal error: seqan/arg_parse.h: No such file or directory
compilation terminated.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by canfirtina** [comment]
Hi,

Sorry for the inconvenience. Makefile should now be working fine for Linux and hopefully for macOS as well. The necessary dependencies are included in "utils" folder. There are some scripts as well under the same folder (for the alignment step).

I also have written some basic documentation (see https://github.com/BilkentCompGen/hercules). It is possible that a more comprehensive documentation will soon be available in readthedocs (or somewhere similar). Thanks for your feedback. Let me know if the issue persists. If not, I will close the issue.

Can

**Comment by colindaven** [comment]
Thanks Can,

that looks great and enough to get me started. The make just completed so I can experiment a little further. Thanks for the docs!

Colin
