### ISSUE TITLE
hercules -2 cannot run

### ISSUE THREAD

**Issue by morispi** [BilkentCompGen/hercules#7]
Hi,

The second part of Hercules doesn't seem to be working. I'm runnng into an error everytime.
Indexing and alignment go fine, following the README instructions, but here is what I get when running the second part of the pipeline:

./hercules -2 -li /mnt/nfs/NGSData/longReads/ADP1/ADP1.fasta -ai alignment.bam -si RealADP1/short.fasta -t 16 -o corRealADP1.fasta
Long Read: /mnt/nfs/NGSData/longReads/ADP1/ADP1.fasta
Short read: RealADP1/short.fasta
Alignment File: alignment.bam
Output file: corRealADP1.fasta
Will output coverage?: No
Min mapping quality: 0
Max Coverage: 1
Filter size: 100
Maximum insertion: 3
Maximum deletion: 10
Match transition probability: 0.7
Insertion transition probability: 0.25
Deletion transition probability: 0.05
Deletion transition factor: 2.5
Match emission probability: 0.97
Mismatch emission probability: 0.01
Insertion emission probability: 0.333333
Max thread: 16
Correction has begun...
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi

Any idea where this could be coming from?

Thank you.
Pierre

**Comment by canfirtina** [comment]
Hello,

Do you use Bowtie2 for the alignment? Can you also provide me with the first few alignment records in your alignment.bam file as a sample (i.e., samtools view alignment.bam | head -10)?

Thanks.

**Comment by morispi** [comment]
Hi,

Yes, I used bowtie2 and the scripts provided in the utils directory for the alignment.
Here are the first alignments:

890338	256	t36channel270read14template	4691	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4693	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4695	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4697	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4699	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4701	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4703	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4705	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4707	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:UU
890338	256	t36channel270read14template	4709	0	6M1I43M1I50M1I18M1I5M1I10M	*	0	0	CTCTCTGCTCACTCTCTCTCTCTCACTCTCTCTCTCTCTCTCTCTCTCTCATATCTCTCTCTCTCTCTCTCTATCTCTCTCTCTCTCTCTCTCGCTGTCACATCTCACACTCTCTCTCTCATCTCTACTCTCTCTCT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:-14	XS:i:-14	XN:i:0	XM:i:9	XO:i:5	XG:i:5	NM:i:14	MD:Z:9T13T26C19C20T2C2T5T1T26	YT:Z:

Tried a few "classical" things that usually cause bugs, such as weird headers in the LR/SR files, but still could not get Hercules to run.

Thanks,
Pierre

**Comment by canfirtina** [comment]
This is interesting because you should not be having some chars (which I assume these are the long read names from your original long read file) in "RNAME" field (3rd column), but you should only have numbers there. I will have two questions:

1) Do you align the compressed short reads (located in RealADP1/compressed_short.fasta) to the compressed long reads (probably located in RealADP1/compressed_ADP1.fasta)?

2) If your answer is yes for the first question, perhaps preprocessing step failed to change the read names for the compressed long reads. Can you confirm this by also providing few read names from the compressed long read file (i.e., grep ">" RealADP1/compressed_ADP1.fasta | head -2)?

Thanks

**Comment by morispi** [comment]
Seems like I tried to align the compressed SR file to the original LR file in my previous run...
Correction step works fine now!

Sorry for the stupid mistake, and thanks a lot for the quick answer!

P

**Comment by canfirtina** [comment]
No worries! Glad that you've solved the problem.

Best,

Can
