### ISSUE TITLE
better use trimmed short reads?

### ISSUE THREAD

**Issue by dcopetti** [BilkentCompGen/hercules#8]
hello,
I wonder if it is better to use trimmed Illumina reads for compression and alignment, or whether different read lengths (still paired) will be an issue.
Also, I have two types of PE libraries (for both I can have >80x coverage): 
PE470, with 2x260 bp reads, or
PE700, with 2x150 bp reads:
Is there a format/length that you think would work better in increasing the breadth of coverage (that seems to be an issue)?
thanks

**Comment by dcopetti** [comment]
Hi,
I wonder if you will have time to address my inquiries (this and https://github.com/BilkentCompGen/hercules/issues/9 ) in the next days.Thanks,
Dario

**Comment by canfirtina** [comment]
Hi @dcopetti 

We haven't done any experiments on the effects of using trimmed Illumina reads. Thus, it is not very easy for me to make a very accurate estimation of this issue. However, I would expect an increased number of alignments and (probably) increased breadth of coverage as the short read lengths become shorter (e.g., by trimming or using different technology). However, if you are using more accurate aligner such as Bowtie2 (especially with the parameters we suggest), I also would expect an increased runtime for the alignment step when the length of short reads is shorter. Unfortunately, I cannot comment on the overall accuracy of the corrected reads using trimmed (shorter) reads as I am not sure whether aligning trimmed reads generates "useful" alignments as these reads will probably align to more locations if "report all alignment" option is selected.

I would suggest you using 2x150bp reads if the accuracy of these two set of short reads (2x260 and 2x150) are similar as I believe you will have a higher breadth of coverage. You can even confirm this by aligning the short reads to a small portion of your long reads (e.g., randomly select 100 of long reads). Then see if you get a higher breadth of coverage by using 2x150 reads.

Thanks.

**Comment by dcopetti** [comment]
Thanks,
So I am using untrimmed PE 700 (2x150 bp) reads, at a coverage of ~40x. Do you think it is enough? Should I add more reads (the PE 470 would be next).
Thanks,
dario

**Comment by canfirtina** [comment]
40X should be sufficient to significantly improve the overall accuracy but, of course, using additional short reads would almost always help. If you have time and/or computational resources you can always use all the short reads you have to correct long reads. This is basically a trade-off between the resources and the overall accuracy of long reads.
